base_url = "https://xadrez.live"
title = "xadrez.live"
description = "Diario pessoal de lives de xadrez."
compile_sass = false
build_search_index = false
generate_feeds = false

[extra]
site_tagline = "praticando xadrez depois dos 40"
