#!/usr/bin/env python3
from __future__ import annotations

import argparse
import subprocess
import tomllib
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
CONTENT_DIR = ROOT / "content" / "fcz"
OUTPUT_PATH = ROOT / "data" / "fcz" / "youtube_video_metadata.toml"
FIELD_SEPARATOR = "\t"


@dataclass(frozen=True)
class Session:
    number: str
    youtube_id: str


def read_front_matter(path: Path) -> dict[str, Any]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("+++\n"):
        return {}
    end = text.find("\n+++", 4)
    if end == -1:
        return {}
    try:
        return tomllib.loads(text[4:end])
    except tomllib.TOMLDecodeError:
        return {}


def session_youtube_ids() -> list[Session]:
    sessions = []
    for path in sorted(CONTENT_DIR.glob("[0-9][0-9][0-9][0-9].md")):
        data = read_front_matter(path)
        if data.get("draft") is True:
            continue
        extra = data.get("extra")
        if not isinstance(extra, dict):
            continue
        if str(extra.get("status_tone") or "").strip().casefold() in {"scheduled", "live"}:
            continue
        youtube_id = str(extra.get("youtube_video_id") or "").strip()
        if youtube_id and youtube_id != "REPLACE_WITH_YOUTUBE_VIDEO_ID":
            sessions.append(Session(str(extra.get("session_number") or path.stem), youtube_id))
    return sessions


def selected_sessions(numbers: set[str] | None, latest: int | None) -> list[Session]:
    sessions = session_youtube_ids()
    if numbers is not None:
        return [session for session in sessions if session.number in numbers]
    if latest is not None and latest > 0:
        return sessions[-latest:]
    return sessions


def int_value(value: str) -> int:
    try:
        return int(value)
    except ValueError:
        return 0


def bool_value(value: str) -> bool:
    return value.strip().casefold() in {"true", "1", "yes"}


def iso_timestamp(timestamp: int) -> str:
    if not timestamp:
        return ""
    return datetime.fromtimestamp(timestamp, tz=timezone.utc).isoformat()


def toml_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def load_existing() -> dict[str, dict[str, Any]]:
    if not OUTPUT_PATH.exists():
        return {}
    try:
        data = tomllib.loads(OUTPUT_PATH.read_text(encoding="utf-8"))
    except tomllib.TOMLDecodeError:
        return {}
    sessions = data.get("sessions")
    return sessions if isinstance(sessions, dict) else {}


def fetch_metadata(session: Session, yt_dlp: str, timeout: int) -> dict[str, Any]:
    fmt = FIELD_SEPARATOR.join(
        [
            "%(id)s",
            "%(live_status)s",
            "%(was_live)s",
            "%(release_timestamp)s",
            "%(timestamp)s",
            "%(upload_date)s",
            "%(duration)s",
            "%(duration_string)s",
            "%(availability)s",
        ]
    )
    proc = subprocess.run(
        [
            yt_dlp,
            "--no-warnings",
            "--skip-download",
            "--print",
            fmt,
            f"https://www.youtube.com/watch?v={session.youtube_id}",
        ],
        check=True,
        capture_output=True,
        text=True,
        timeout=timeout,
    )
    line = proc.stdout.strip().splitlines()[-1]
    fields = line.split(FIELD_SEPARATOR)
    if len(fields) != 9:
        raise RuntimeError(f"unexpected yt-dlp metadata output for {session.youtube_id}")
    release_timestamp = int_value(fields[3])
    published_timestamp = int_value(fields[4])
    duration_seconds = int_value(fields[6])
    return {
        "youtube_video_id": fields[0],
        "url": f"https://www.youtube.com/watch?v={fields[0]}",
        "live_status": fields[1],
        "was_live": bool_value(fields[2]),
        "release_timestamp": release_timestamp,
        "release_at": iso_timestamp(release_timestamp),
        "published_timestamp": published_timestamp,
        "published_at": iso_timestamp(published_timestamp),
        "upload_date": fields[5],
        "duration_seconds": duration_seconds,
        "duration": fields[7],
        "availability": fields[8],
    }


def write_metadata(sessions: dict[str, dict[str, Any]]) -> bool:
    lines = [
        "# Generated by scripts/update_youtube_video_metadata.py.",
        f"updated_at = {toml_string(datetime.now(timezone.utc).isoformat())}",
        "",
    ]
    for number in sorted(sessions):
        data = sessions[number]
        lines.append(f'[sessions.{toml_string(number)}]')
        for key in (
            "youtube_video_id",
            "url",
            "live_status",
            "was_live",
            "release_timestamp",
            "release_at",
            "published_timestamp",
            "published_at",
            "upload_date",
            "duration_seconds",
            "duration",
            "availability",
        ):
            value = data.get(key)
            if isinstance(value, bool):
                rendered = "true" if value else "false"
            elif isinstance(value, int):
                rendered = str(value)
            else:
                rendered = toml_string(str(value or ""))
            lines.append(f"{key} = {rendered}")
        lines.append("")
    content = "\n".join(lines)
    if OUTPUT_PATH.exists() and OUTPUT_PATH.read_text(encoding="utf-8") == content:
        return False
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(content, encoding="utf-8")
    return True


def update(sessions: list[Session], yt_dlp: str, timeout: int) -> int:
    existing = load_existing()
    changed = 0
    for session in sessions:
        try:
            existing[session.number] = fetch_metadata(session, yt_dlp, timeout)
        except (subprocess.CalledProcessError, subprocess.TimeoutExpired, RuntimeError) as error:
            print(f"{session.number}: warning: {error}")
            continue
        changed += 1
        print(f"{session.number}: metadata updated")
    write_metadata(existing)
    print(f"summary: {changed} fetched, {len(sessions) - changed} failed")
    return changed


def main() -> int:
    parser = argparse.ArgumentParser(description="Fetch YouTube VOD metadata used by session timestamp calculations.")
    parser.add_argument("sessions", nargs="*", help="Optional session numbers, e.g. 0051.")
    parser.add_argument("--latest", type=int, help="Only process the latest N ended sessions with YouTube videos.")
    parser.add_argument("--yt-dlp", default="yt-dlp")
    parser.add_argument("--timeout", type=int, default=30)
    args = parser.parse_args()

    sessions = selected_sessions(set(args.sessions) if args.sessions else None, args.latest)
    update(sessions, args.yt_dlp, args.timeout)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
