#!/usr/bin/env python3
"""Upload a session og_image as the YouTube video thumbnail."""
from __future__ import annotations

import argparse
import hashlib
import json
import mimetypes
import sys
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Any

from update_youtube_chapters import ENV_PATH, access_token, env_value, load_env_file


ROOT = Path(__file__).resolve().parents[1]
CONTENT_DIR = ROOT / "content" / "fcz"
STATIC_DIR = ROOT / "static"
PUBLISHED_ASSETS_PATH = ROOT / "data" / "fcz" / "youtube_published_assets.toml"
YOUTUBE_UPLOAD_API = "https://www.googleapis.com/upload/youtube/v3"
MAX_THUMBNAIL_BYTES = 2 * 1024 * 1024


def read_front_matter(path: Path) -> dict[str, Any]:
    import tomllib

    text = path.read_text(encoding="utf-8")
    if not text.startswith("+++\n"):
        return {}
    end = text.find("\n+++", 4)
    if end == -1:
        return {}
    try:
        return tomllib.loads(text[4:end])
    except tomllib.TOMLDecodeError:
        return {}


def session_paths(numbers: set[str]) -> list[Path]:
    paths = []
    for number in sorted(numbers):
        path = CONTENT_DIR / f"{number.zfill(4)}.md"
        if not path.exists():
            raise RuntimeError(f"sessão não encontrada: {number}")
        paths.append(path)
    return paths


def thumbnail_for_session(path: Path) -> tuple[str, str, Path]:
    front_matter = read_front_matter(path)
    extra = front_matter.get("extra")
    if not isinstance(extra, dict):
        raise RuntimeError(f"{path}: seção [extra] não encontrada")

    video_id = str(extra.get("youtube_video_id") or "").strip()
    if not video_id or video_id == "REPLACE_WITH_YOUTUBE_VIDEO_ID":
        raise RuntimeError(f"{path}: youtube_video_id não configurado")

    og_image = str(extra.get("og_image") or "").strip()
    if not og_image:
        raise RuntimeError(f"{path}: og_image não configurado")
    if "://" in og_image:
        raise RuntimeError(f"{path}: og_image deve ser um caminho local do site, não URL absoluta")

    relative = og_image.lstrip("/")
    image_path = STATIC_DIR / relative
    if not image_path.exists():
        raise RuntimeError(f"{path}: thumbnail não encontrada em {image_path.relative_to(ROOT)}")
    if not image_path.is_file():
        raise RuntimeError(f"{path}: thumbnail não é arquivo: {image_path.relative_to(ROOT)}")
    return path.stem, video_id, image_path


def content_type(path: Path) -> str:
    guessed = mimetypes.guess_type(path.name)[0]
    if guessed in {"image/jpeg", "image/png"}:
        return guessed
    raise RuntimeError(f"{path}: YouTube aceita thumbnail JPG ou PNG; tipo detectado: {guessed or 'desconhecido'}")


def file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def read_published_assets() -> dict[str, Any]:
    import tomllib

    if not PUBLISHED_ASSETS_PATH.exists():
        return {}
    try:
        data = tomllib.loads(PUBLISHED_ASSETS_PATH.read_text(encoding="utf-8"))
    except tomllib.TOMLDecodeError:
        return {}
    return data if isinstance(data, dict) else {}


def toml_quote(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def write_published_assets(data: dict[str, Any]) -> None:
    lines = ["# Generated by scripts/update_youtube_thumbnail.py.", ""]
    thumbnails = data.get("thumbnails")
    if isinstance(thumbnails, dict):
        for session_number in sorted(thumbnails):
            item = thumbnails.get(session_number)
            if not isinstance(item, dict):
                continue
            lines.append(f'[thumbnails."{session_number}"]')
            for key in ("youtube_video_id", "path", "sha256"):
                value = str(item.get(key) or "")
                lines.append(f"{key} = {toml_quote(value)}")
            lines.append("")
    PUBLISHED_ASSETS_PATH.parent.mkdir(parents=True, exist_ok=True)
    PUBLISHED_ASSETS_PATH.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def published_thumbnail(data: dict[str, Any], session_number: str) -> dict[str, Any]:
    thumbnails = data.get("thumbnails")
    if not isinstance(thumbnails, dict):
        return {}
    item = thumbnails.get(session_number)
    return item if isinstance(item, dict) else {}


def remember_thumbnail(data: dict[str, Any], session_number: str, video_id: str, image_path: Path, sha256: str) -> None:
    thumbnails = data.setdefault("thumbnails", {})
    if not isinstance(thumbnails, dict):
        data["thumbnails"] = thumbnails = {}
    thumbnails[session_number] = {
        "youtube_video_id": video_id,
        "path": image_path.relative_to(ROOT).as_posix(),
        "sha256": sha256,
    }


def upload_thumbnail(token: str, video_id: str, image_path: Path) -> dict[str, Any]:
    data = image_path.read_bytes()
    url = f"{YOUTUBE_UPLOAD_API}/thumbnails/set?{urllib.parse.urlencode({'videoId': video_id, 'uploadType': 'media'})}"
    request = urllib.request.Request(
        url,
        method="POST",
        data=data,
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/json",
            "Content-Type": content_type(image_path),
            "Content-Length": str(len(data)),
            "User-Agent": "xadrez-live-youtube-thumbnail/1.0",
        },
    )
    try:
        with urllib.request.urlopen(request, timeout=60) as response:
            return json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as error:
        detail = error.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"YouTube thumbnail upload failed with HTTP {error.code}: {detail}") from error
    except urllib.error.URLError as error:
        raise RuntimeError(f"YouTube thumbnail upload failed: {error.reason}") from error


def main() -> int:
    load_env_file(ENV_PATH)
    parser = argparse.ArgumentParser(description="Upload session og_image files as YouTube thumbnails.")
    parser.add_argument("sessions", nargs="+", help="Session numbers, e.g. 0053 0054.")
    parser.add_argument("--write", action="store_true", help="Upload to YouTube. Without this flag, only print a dry run.")
    parser.add_argument("--force", action="store_true", help="Upload even if the local hash matches the last recorded upload.")
    args = parser.parse_args()

    try:
        items = [thumbnail_for_session(path) for path in session_paths(set(args.sessions))]
    except RuntimeError as error:
        parser.error(str(error))

    published_assets = read_published_assets()
    checked_items = []
    for session_number, video_id, image_path in items:
        size = image_path.stat().st_size
        if size > MAX_THUMBNAIL_BYTES:
            parser.error(
                f"{session_number}: thumbnail tem {size} bytes; YouTube permite no máximo {MAX_THUMBNAIL_BYTES} bytes"
            )
        sha256 = file_sha256(image_path)
        remembered = published_thumbnail(published_assets, session_number)
        unchanged = (
            not args.force
            and remembered.get("youtube_video_id") == video_id
            and remembered.get("path") == image_path.relative_to(ROOT).as_posix()
            and remembered.get("sha256") == sha256
        )
        status = "unchanged" if unchanged else "pending"
        print(f"{session_number}: {video_id} <- {image_path.relative_to(ROOT)} ({size} bytes, {status})")
        checked_items.append((session_number, video_id, image_path, sha256, unchanged))

    if not args.write:
        pending = sum(1 for *_, unchanged in checked_items if not unchanged)
        print(f"dry run: {pending} pending, {len(checked_items) - pending} unchanged; use --write to upload")
        return 0

    client_id = env_value("YOUTUBE_CLIENT_ID")
    client_secret = env_value("YOUTUBE_CLIENT_SECRET")
    refresh_token = env_value("YOUTUBE_REFRESH_TOKEN")
    if not client_id or not client_secret:
        raise SystemExit("error: set YOUTUBE_CLIENT_ID and YOUTUBE_CLIENT_SECRET in .env")
    if not refresh_token:
        raise SystemExit("error: set YOUTUBE_REFRESH_TOKEN in .env or run `just youtube-chapters-authorize` first")

    token = access_token(client_id, client_secret, refresh_token)
    uploaded = 0
    skipped = 0
    for session_number, video_id, image_path, sha256, unchanged in checked_items:
        if unchanged:
            skipped += 1
            print(f"{session_number}: thumbnail unchanged, skipping upload")
            continue
        try:
            upload_thumbnail(token, video_id, image_path)
        except RuntimeError as error:
            print(f"{session_number}: {error}", file=sys.stderr)
            continue
        uploaded += 1
        remember_thumbnail(published_assets, session_number, video_id, image_path, sha256)
        write_published_assets(published_assets)
        print(f"{session_number}: uploaded thumbnail")
    failed = len(checked_items) - uploaded - skipped
    print(f"summary: {uploaded} uploaded, {skipped} unchanged, {failed} failed")
    return 0 if failed == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
